import LegalPage from "@/components/LegalPage";
const contact = "hello@small.academy";
export default function Privacy() { return <LegalPage title="Privacy notice" description="How Echoes of the Past handles information when you browse, create, or contact the project." updated="29 September 2026" sections={[
  { title: "Who is responsible", body: <p>Asociația Small Academy coordinates the Echoes of the Past Erasmus+ project and is responsible for this website. For privacy questions, access, correction, deletion, or a concern about how information is handled, email <a href={`mailto:${contact}?subject=Echoes%20of%20the%20Past%20privacy%20request`}>{contact}</a>. Please do not include sensitive personal information in your first message.</p> },
  { title: "What the platform processes", body: <ul><li><strong>Anonymous visitor session.</strong> Supabase creates an anonymous technical identifier so the site can protect the shared AI service from misuse and apply the daily request allowance. It is not a public profile and does not require a name, email address, or password.</li><li><strong>AI requests and results.</strong> When you use an AI tool, the prompt and any image you choose to send are transmitted to the central service so it can create the requested result. The browser keeps only a request identifier and a one-way digest for safe retries; it does not keep the prompt in that retry record.</li><li><strong>Uploaded and generated media.</strong> Images you upload and AI-created images, audio, or video may be stored in the project media storage so the requested feature can return a result. Do not upload personal, sensitive, confidential, or copyrighted material unless you have permission.</li><li><strong>Analytics and technical requests.</strong> GoatCounter records aggregated page-view information to help the project understand reach. OpenStreetMap receives ordinary map-tile requests when you open the map. Hosting, security, and service providers may also process limited technical information such as IP address, browser information, timestamps, and error logs to deliver and protect their services.</li></ul> },
  { title: "Service providers", body: <div className="legal-table-wrap"><table><thead><tr><th>Provider</th><th>Why it is used</th></tr></thead><tbody><tr><td>GitHub Pages</td><td>Hosts the public website.</td></tr><tr><td>Supabase</td><td>Provides anonymous sessions, protected service functions, request limits, and media storage.</td></tr><tr><td>Google Gemini and OpenAI</td><td>Process only the content sent to the selected AI feature to generate text, images, audio, video, or image analysis. Availability depends on the feature enabled by the project.</td></tr><tr><td>GoatCounter</td><td>Provides privacy-conscious, aggregate page analytics. It is configured without advertising trackers.</td></tr><tr><td>OpenStreetMap</td><td>Supplies map tiles and attribution for the archive map.</td></tr></tbody></table></div> },
  { title: "Retention and deletion", body: <><p>Anonymous service records and stored generated media are kept for no more than 30 days for service operation, safety, troubleshooting, and abuse prevention, then deleted through the project’s retention process. Aggregate analytics are kept by GoatCounter according to its service settings. Public archive material stays available while it is part of the project collection.</p><p>If you created material or believe that a record concerns you, email <a href={`mailto:${contact}?subject=Echoes%20of%20the%20Past%20deletion%20request`}>{contact}</a> with the page link, approximate date, and enough detail to locate it. We may need to confirm that you are entitled to make the request before acting.</p></> },
  { title: "Your choices and rights", body: <p>You can browse the archive without creating an account. You can avoid AI features and the map if you do not want to send content to their respective services. Depending on applicable law, you may have rights to access, correct, erase, restrict, object to, or receive a copy of personal information. You may also complain to your local data-protection authority. Contact us first so we can try to resolve the matter.</p> },
  { title: "Changes", body: <p>We will update this notice when the platform or its processing changes materially. The date at the top shows the most recent revision.</p> },
]}/>; }
